// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwGkEqpMSncSYc4FluHrB2hJ41q2Zvf9A',
    appId: '1:414564563740:web:f79e62a9c391cec70bd8d9',
    messagingSenderId: '414564563740',
    projectId: 'android-club-bdf3e',
    authDomain: 'android-club-bdf3e.firebaseapp.com',
    storageBucket: 'android-club-bdf3e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsV2acO8j24GjEiNUbMx9PWxpDiukvOAs',
    appId: '1:414564563740:android:83e853c8a887761f0bd8d9',
    messagingSenderId: '414564563740',
    projectId: 'android-club-bdf3e',
    storageBucket: 'android-club-bdf3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd56_NnJELTzcdtqx8Bpei1YKfNFxVi7w',
    appId: '1:414564563740:ios:18790e86d7b0930b0bd8d9',
    messagingSenderId: '414564563740',
    projectId: 'android-club-bdf3e',
    storageBucket: 'android-club-bdf3e.firebasestorage.app',
    iosBundleId: 'com.example.ac2425',
  );
}
